### ISSUE TITLE
Sometimes throws java.lang.NumberFormatException

### ISSUE THREAD

**Issue by ghost** [jezhumble/javasysmon#17]
### Description

JVM works on Ubuntu

Scheduled task inside JVM periodically ask system statistics and catch following exceptions:
- java.lang.NumberFormatException: null
  at java.lang.Long.parseLong(Unknown Source)
  at java.lang.Long.parseLong(Unknown Source)
  at com.jezhumble.javasysmon.LinuxMonitor.uptimeInSeconds(LinuxMonitor.java:105)
  at com.jezhumble.javasysmon.JavaSysMon.uptimeInSeconds(JavaSysMon.java:156)
- java.lang.NumberFormatException: null
  at java.lang.Long.parseLong(Unknown Source)
  at java.lang.Long.parseLong(Unknown Source)
  at com.jezhumble.javasysmon.LinuxMonitor.physical(LinuxMonitor.java:66)
  at com.jezhumble.javasysmon.JavaSysMon.physical(JavaSysMon.java:192)

I can't detect some preconditions of specified errors. Time between exceptions aren't fixed.
Files in /proc are exists and contains required values.
### Various system info

uname -a
Linux xxxxx-Ubuntu SMP Tue Aug 30 19:33:19 UTC 2011 x86_64 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=10.10
DISTRIB_CODENAME=maverick
DISTRIB_DESCRIPTION="Ubuntu 10.10"

cat  /proc/meminfo
MemTotal:        1697024 kB
MemFree:          864440 kB
... etc

cat /proc/uptime
80084.28 149307.49

**Comment by oldirtybasti** [comment]
I can confirm this bug on Ubuntu. Sometimes 

JavaSysMon monitor = new JavaSysMon();
ProcessInfo[] processes = monitor.processTable();

crashes due to a NumberFormatException. The Number that was parsed contains "slee". I think some process might be sleeping?

Would be greate if you could look into that. Great library by the way, I use it every day!

**Comment by johnkajava** [comment]
Even I have the same problem. Any work around please.

<a href="http://wisentechnologies.com/it-courses/java-training.aspx" title="Java Training in Chennai">Java Training  in Chennai</a> | <a href="http://wisentechnologies.com/it-courses/java-training.aspx" title="Java Training Institutes in Chennai">Java Training  Institutes in Chennai</a>
