### ISSUE TITLE
windows 32bit dll was incorrectly compiled as 64bit

### ISSUE THREAD

**Issue by romikk** [jezhumble/javasysmon#35]
Latest javasysmon release has incorrectly compiled dll:

D:\APPS>"C:\Program Files\Java\jdk1.6.0_24\bin\java" -jar ./lib/javasysmon-0.3.5.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Documents and Settings\romikk\Local Settings\Temp\2\javasysmo5686058043554074094.dll: Can't l
oad AMD 64-bit .dll on a IA 32-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1803)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1699)
        at java.lang.Runtime.load0(Runtime.java:770)
        at java.lang.System.load(System.java:1003)
        at com.jezhumble.javasysmon.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:16)
        at com.jezhumble.javasysmon.WindowsMonitor.<clinit>(WindowsMonitor.java:11)
        at com.jezhumble.javasysmon.JavaSysMon.<clinit>(JavaSysMon.java:53)
Could not find the main class: com.jezhumble.javasysmon.JavaSysMon. Program will exit.

**Comment by goxr3plus** [comment]
I have exactly the same problem for windows 7 32 bit . The jar is compiled in Windows 10 64 bit and working perfect but on the Windows 7 32 bit , i am getting this error .

Have you found any work around?

**Comment by goxr3plus** [comment]
I created a fixed .jar version and uploaded it on this repository -> https://github.com/goxr3plus/javasysmon

**Comment by sco-tt** [comment]
I know this has been reported elsewhere (and in the parent thread) but I got the same error on javasysmon-0.3.5.jar

Using javasysmon2 (author is @goxr3plus, who has commented above) fixes this issue on my project. 

Thanks @goxr3plus!
